# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Ivan Pizhenko, 2025. All rights reserved.
# See file LICENSE for more information.

NAME:=hdist
MAN_SHORT_DESC:=compute Hamming distance

include ../mk/common.mk
